# Answer Options API

# Get all answer options
# ✅ Should return 200 OK with a list of answer options
# Admin-only
GET {{baseUrl}}/answeroption
Authorization: Bearer {{$dotenv TOKEN}}

###

# Get answer option
# ❌✅ Should return 200 OK with an answer option
# @prompt id
GET {{baseUrl}}/answeroption/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update answer option
# ❌✅ Should return 204 No Content
# Admin-only
# @prompt id
PUT {{baseUrl}}/answeroption/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add answer option
# ❌ Should return 201 Created with a created answer option
# Admin-only

POST {{baseUrl}}/answeroption
Authorization: Bearer {{$dotenv TOKEN}}

###

# Delete answer option
# ❌✅ Should return 204 No Content
# Admin-only
# @prompt id
DELETE {{baseUrl}}/answeroption/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}