# Answers API

# Get all answers
# ✅ Should return 200 OK with a list of answers
GET {{baseUrl}}/answer
Authorization: Bearer {{$dotenv TOKEN}}

###

# Get answer
# ✅ Should return 200 OK with an answer
# @prompt id
GET {{baseUrl}}/answer/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add answer
# ✅ Should return 201 Created with a created answer
# @prompt resultId
# @prompt questionId
# @prompt selectedOption
POST {{baseUrl}}/answer
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "resultId": "{{resultId}}",
    "questionId": "{{questionId}}",
    "selectedOptions": ["{{selectedOption}}"]
}

###

# Delete answer
# ✅ Should return 204 No Content
# @prompt id
# Admin-only
DELETE {{baseUrl}}/answer/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}
