# Answers API

# Get all items
# ✅ Should return 200 OK with a list of items
GET {{baseUrl}}/answer
Authorization: Bearer {{$dotenv TOKEN}}

###

# Get item
# Should return 200 OK with an item
GET {{baseUrl}}/answer/1
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update item
# Should return 204 No Content
PUT {{baseUrl}}/answer/1
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add item
# Should return 201 Created with a created item
POST {{baseUrl}}/answer
Authorization: Bearer {{$dotenv TOKEN}}

###

# Delete item
# Should return 204 No Content
DELETE {{baseUrl}}/answer/1
Authorization: Bearer {{$dotenv TOKEN}}
