# Answer Options API

# Get all items
# ✅ Should return 200 OK with a list of items
# Admin
GET {{baseUrl}}/answeroption
Authorization: Bearer {{$dotenv TOKEN}}

###

# Get item
# Should return 200 OK with an item
GET {{baseUrl}}/answeroption/1
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update item
# Should return 204 No Content
# Admin
PUT {{baseUrl}}/answeroption/1
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add item
# Should return 201 Created with a created item
# Admin
POST {{baseUrl}}/answeroption
Authorization: Bearer {{$dotenv TOKEN}}

###

# Delete item
# Should return 204 No Content
# Admin
DELETE {{baseUrl}}/answeroption/1
Authorization: Bearer {{$dotenv TOKEN}}