# Questions API

# Get all questions
# ✅ Should return 200 OK with a list of questions
# Admin-only
GET {{baseUrl}}/question
Authorization: Bearer {{$dotenv TOKEN}}

###

# Get question
# ✅ Should return 200 OK with a question
# @prompt id
GET {{baseUrl}}/question/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update question
# ❌ Should return 204 No Content
# Admin-only
# @prompt id

PUT {{baseUrl}}/question/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add question
# ✅ Should return 201 Created with a created question
# Admin-only
# @prompt quizId
POST {{baseUrl}}/question
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "text": "test",
    "topics": [],
    "difficulty": 1,
    "answeroptions": [],
    "quizId": {{quizId}}
}

###

# Delete question
# ✅ Should return 204 No Content
# Admin-only
# @prompt id
DELETE {{baseUrl}}/question/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}