# Quizzes API

# Get all items
# ✅ Should return 200 OK with a list of items
GET {{baseUrl}}/quiz

###

# Get item
# Should return 200 OK with an item
GET {{baseUrl}}/quiz/1
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update item
# Should return 204 No Content
# Admin
PUT {{baseUrl}}/quiz/1
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add item
# Should return 201 Created with a created item
# Admin
POST {{baseUrl}}/quiz
Authorization: Bearer {{$dotenv TOKEN}}

###

# Delete item
# Should return 204 No Content
# Admin
DELETE {{baseUrl}}/quiz/1
Authorization: Bearer {{$dotenv TOKEN}}