# Quizzes API

# Get all quizzes
# ✅ Should return 200 OK with a list of quizzes
GET {{baseUrl}}/quiz

###

# Get quiz
# ✅ Should return 200 OK with a quiz
# @prompt id
GET {{baseUrl}}/quiz/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update quiz
# ❌ Should return 204 No Content
# Admin-only
# @prompt id

PUT {{baseUrl}}/quiz/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Add quiz
# ✅ Should return 201 Created with a created quiz
# Admin-only
POST {{baseUrl}}/quiz
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "title": "test",
    "questions": []
}

###

# Delete quiz
# ✅ Should return 204 No Content
# Admin-only
# @prompt id
DELETE {{baseUrl}}/quiz/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}