# Users API

# Get all users
# ✅ Should return 200 OK with a list of users
# Admin-only
GET {{baseUrl}}/user
Authorization: Bearer {{$dotenv TOKEN}}

###

# Get user
# ✅ Should return 200 OK with a user
# @prompt id
GET {{baseUrl}}/user/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}

###

# Update user
# ❌ Should return 204 No Content
# Self- or admin- only
# @prompt id

PUT {{baseUrl}}/user/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

###

# Add user
# ✅ Should return 201 Created with a created user
POST {{baseUrl}}/user
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "age": 1,
    "interests": []
}

###

# Delete user
# ❌ Should return 204 No Content
# Self- or admin- only
# @prompt id

DELETE {{baseUrl}}/user/{{id}}
Authorization: Bearer {{$dotenv TOKEN}}